language: python
cache: pip

python: 3.7

jobs:
  include:
    - stage: lint
      addons: {}
      before_install: skip
      install:
        - pip install flake8 flake8-import-order planemo
        - planemo --version
      script:
        - set -e
        - planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive .

    - stage: test
      script:
        - set -e
        - planemo test

before_install:
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME

install:
  - pip install planemo
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - conda install -y -c conda-forge conda=4.8.2
  - planemo --version
  - conda --version

