language: python
cache: pip

python: 3.7

jobs:
  include:
    - stage: lint
      addons: {}
      before_install: skip
      install:
        - pip install flake8 flake8-import-order planemo Pygments
        - planemo --version
      script:
        - set -e
        - planemo lint
        - planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive .

    - stage: test
      script:
        - set -e
        - perl script/CLIFinder.pl --first test-data/one.fastq --name test --second test-data/two.fastq --ref test-data/genome.fa --build_index --TE test-data/TE.fa --build_TE --html test-data/myres.html --html_path test-data/myfiles --size_insert 500 --size_read 100 --pourcentage 30 --BDir 0 --minL1 30 --mis_L1 6 --threads 16
        - planemo --verbose test --galaxy_python_version "$GALAXY_PYTHON_VERSION"

before_install:
  - export GALAXY_PYTHON_VERSION="3.7"
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME

install:
  - pip install planemo
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - conda install -y -c conda-forge conda=4.8.2
  - planemo --version
  - conda --version
  - planemo conda_install --global .

