name: Python CI/Planemo

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install flake8 flake8-import-order planemo Pygments
      - name: Check dependencies
        run: planemo --version
      - name: Lint with planemo & flake8
        run: planemo lint
      - name: Shed lint with planemo
        run: planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive .

  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Galaxy
        uses: actions/cache@v4
        with:
          path: ~/.planemo/gx_repo
          key: ${{ runner.os }}-gx_repo
          restore-keys: |
            ${{ runner.os }}-gx_repo
      - name: Install Planemo
        run: pip install Planemo
      - name: Initialize conda
        run: planemo conda_init
      - name: Check Planemo version
        run: planemo --version
      - name: Check Conda version
        run: conda --version
      - name: Run tests
        run: planemo test

  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install flake8 flake8-import-order planemo Pygments
      - name: Check dependencies
        run: planemo --version
      - name: Deploy
        run: planemo shed_update --shed_target toolshed --shed_key_from_env ${{ secrets.SHED_KEY }} --force_repository_creation .